"""dsgap.py BOARD.kicad_pcb [--out docs/PLACEMENT_DATASHEET_CHECK.md] [--keep tools/placeaudit_keep.json] [--warn]   (2026-10-04)
Datasheet placement check of every part, measured on the board itself (read-only, KiCad python).

docs/sensitivity.json gives each part its datasheet rule: anchor pin (REF.PIN), max_mm, sensitivity and source. Its
stored gap_mm values were measured on the old parts.json poses, so this tool measures the live gap instead:
the pad-edge gap (pad bounding boxes) from the part's pad to the nearest anchor-IC pad on a SHARED non-GND net. That
follows pin swaps (e.g. EXP_ANA_MON moved from U8.28 to U8.15 in cp4b2) and multi-pin supplies (J10 has four VBUS
pins). With no shared net it falls back to the anchor pin itself. Parts that are no longer on the board (removed in
the BOM simplification) and anchors that are nets ("net:X", test points) are counted, not measured.

live_gaps(board, sens_parts) -> {ref: {gap, max, anchor, sens, sides, note}} is also used by placeaudit.py (OVER).
--out writes the per-IC table: each IC's datasheet layout rules (section / page) and every part bound to it with the
measured gap, its budget and the verdict (OK, OVER, or KEEP with the reason from placeaudit_keep.json).
Exit 1 when a part is over budget without a reason (--warn: report only, exit 0).
  python dsgap.py --selftest"""
import io
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def box_gap(a, c):
    """edge gap of two (x0, y0, x1, y1) boxes; 0 when they touch or overlap"""
    dx = max(0.0, max(a[0], c[0]) - min(a[2], c[2]))
    dy = max(0.0, max(a[1], c[1]) - min(a[3], c[3]))
    return math.hypot(dx, dy)


def nearest(mine, cand):
    """mine, cand: [(name, net, box)] -> (gap, cand name) over pairs; same-net pairs only when any exist"""
    pairs = [(m, c) for m in mine for c in cand if m[1] == c[1]] or [(m, c) for m in mine for c in cand]
    return min((box_gap(m[2], c[2]), c[0]) for m, c in pairs)


def live_gaps(board, sens_parts):
    def bb(p):
        r = p.GetBoundingBox()
        return (r.GetLeft() / 1e6, r.GetTop() / 1e6, r.GetRight() / 1e6, r.GetBottom() / 1e6)

    fps = {f.GetReference(): f for f in board.GetFootprints()}
    out = {}
    for ref, e in sens_parts.items():
        a, m = e.get('anchor'), e.get('max_mm')
        if not a or m is None or ref not in fps or a.startswith('net:') or '.' not in a:
            continue
        ar, ap = a.split('.', 1)
        if ar not in fps:
            continue
        nets = {p.GetNetname() for p in fps[ref].Pads()} - {'GND', ''}
        cand = [(p.GetNumber(), p.GetNetname(), bb(p)) for p in fps[ar].Pads() if p.GetNetname() in nets]
        note = ''
        pin = [p for p in fps[ar].Pads() if p.GetNumber() == ap]
        if not cand:
            cand = [(p.GetNumber(), p.GetNetname(), bb(p)) for p in pin]
            note = f'no shared net with {a}'
        elif pin and pin[0].GetNetname() not in nets:
            note = f'{a} no longer carries its net; nearest pin on it: ' + ','.join(sorted({c[0] for c in cand}))
        if not cand:
            continue
        mine = [(p.GetNumber(), p.GetNetname(), bb(p)) for p in fps[ref].Pads()]
        g, pn = nearest(mine, cand)
        sd = lambda f: 'B' if f.IsFlipped() else 'F'  # noqa: E731
        out[ref] = {'gap': round(g, 3), 'max': m, 'anchor': f'{ar}.{pn}', 'sens': e.get('sensitivity', ''),
                    'sides': sd(fps[ref]) + sd(fps[ar]), 'note': note, 'ic': e.get('ic') or ar,
                    'role': e.get('role', ''), 'source': e.get('source', '')}
    return out


def report(gaps, sens, keep):
    over = [r for r, g in gaps.items() if g['gap'] > g['max']]
    unkept = [r for r in over if r not in keep]
    gone = [r for r, e in sens['parts'].items() if e.get('anchor') and e.get('max_mm') is not None and r not in gaps
            and not str(e.get('anchor')).startswith('net:')]
    md = ['# Placement against the datasheet layout guides', '',
          'Generated by `tools/dsgap.py` from the board and `docs/sensitivity.json` (each rule quotes its datasheet '
          'section and page). Gap = pad-edge distance from the part to the nearest pin of its IC on a shared net, '
          'measured on the board. Budgets marked "EMC practice" in a source are our tightening of the datasheet\'s '
          '"close to the pin".', '',
          f'- **{len(gaps)} parts measured, {len(gaps) - len(over)} within budget, {len(over)} over** '
          f'({len(over) - len(unkept)} justified in `tools/placeaudit_keep.json`, **{len(unkept)} unjustified**).',
          f'- {len(gone)} rules belong to parts removed in the BOM simplification (not on the board).', '']
    by_ic = {}
    for r, g in gaps.items():
        by_ic.setdefault(g['ic'], []).append(r)
    for ic in sorted(by_ic, key=lambda k: (k not in sens.get('ics', {}), k)):
        info = sens.get('ics', {}).get(ic, {})
        md += [f"## {ic}{(' ' + info['mpn']) if info.get('mpn') else ''}"
               f"{(' (' + info['datasheet'] + ')') if info.get('datasheet') else ''}", '']
        for rule in info.get('layout_rules', []):
            md.append(f"- {rule['rule']} *({rule.get('page', '')})*")
        md += ['', '| Part | Role | Side / IC side | Nearest pin | Gap mm | Budget mm | Verdict |', '|---|---|---|---|---|---|---|']
        for r in sorted(by_ic[ic], key=lambda x: -(gaps[x]['gap'] - gaps[x]['max'])):
            g = gaps[r]
            v = 'OK' if g['gap'] <= g['max'] else ('KEEP: ' + keep[r] if r in keep else '**OVER**')
            if g['note']:
                v += f" ({g['note']})"
            md.append(f"| {r} | {g['role'][:60]} | {g['sides'][0]} / {g['sides'][1]} | {g['anchor']} | {g['gap']:.2f} "
                      f"| {g['max']} ({g['sens']}) | {v} |")
        md.append('')
    return md, over, unkept


def main(argv):
    if '--selftest' in argv:
        assert box_gap((0, 0, 1, 1), (2, 0, 3, 1)) == 1.0 and box_gap((0, 0, 1, 1), (0.5, 0.5, 2, 2)) == 0.0
        assert abs(box_gap((0, 0, 1, 1), (4, 5, 6, 6)) - 5.0) < 1e-9
        # same-net pairs win over a nearer pad of another net
        g, pin = nearest([('1', 'A', (0, 0, 1, 1)), ('2', 'B', (2, 0, 3, 1))], [('7', 'A', (5, 0, 6, 1)), ('8', 'B', (3.5, 0, 4, 1))])
        assert (g, pin) == (0.5, '8'), (g, pin)
        g, pin = nearest([('1', 'A', (0, 0, 1, 1))], [('9', 'Z', (1.5, 0, 2, 1))])
        assert (g, pin) == (0.5, '9')
        gaps = {'C1': {'gap': 2.5, 'max': 2.0, 'anchor': 'U1.3', 'sens': 'high', 'sides': 'FF', 'note': '', 'ic': 'U1', 'role': 'dec', 'source': ''},
                'C2': {'gap': 0.5, 'max': 2.0, 'anchor': 'U1.4', 'sens': 'high', 'sides': 'FF', 'note': '', 'ic': 'U1', 'role': 'dec', 'source': ''},
                'C3': {'gap': 9.0, 'max': 3.0, 'anchor': 'U1.5', 'sens': 'high', 'sides': 'BF', 'note': '', 'ic': 'U1', 'role': 'dec', 'source': ''}}
        sens = {'ics': {'U1': {'mpn': 'X1', 'layout_rules': [{'rule': 'caps close', 'page': 'p.9'}]}},
                'parts': {'C1': {'anchor': 'U1.3', 'max_mm': 2}, 'C9': {'anchor': 'U1.1', 'max_mm': 1}}}
        md, over, unkept = report(gaps, sens, {'C1': 'corner of the pin column'})
        txt = '\n'.join(md)
        assert sorted(over) == ['C1', 'C3'] and unkept == ['C3'], (over, unkept)
        assert '1 justified' in txt and '**1 unjustified**' in txt and '1 rules belong to parts removed' in txt
        assert 'KEEP: corner of the pin column' in txt and '| C3 |' in txt and 'caps close *(p.9)*' in txt
        print('dsgap selftest OK')
        return 0
    import pcbnew
    src = argv[1]
    opt = lambda k, d: argv[argv.index(k) + 1] if k in argv else d  # noqa: E731
    sens = json.load(io.open(opt('--sens', os.path.join(HERE, '..', 'docs', 'sensitivity.json')), encoding='utf-8'))
    kf = opt('--keep', os.path.join(HERE, 'placeaudit_keep.json'))
    keep = {k: v for k, v in json.load(io.open(kf, encoding='utf-8')).items() if not k.startswith('_')} if os.path.isfile(kf) else {}
    gaps = live_gaps(pcbnew.LoadBoard(src), sens['parts'])
    md, over, unkept = report(gaps, sens, keep)
    if '--out' in argv:
        io.open(opt('--out', ''), 'w', encoding='utf-8', newline='\n').write('\n'.join(md) + '\n')
    print(f'dsgap: {len(gaps)} parts measured, {len(over)} over budget, {len(unkept)} unjustified'
          + (': ' + ', '.join(unkept) if unkept else ''))
    return 1 if unkept and '--warn' not in argv else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
